version: '2'
services:
    api:
      build: ./apis 
      depends_on:
          - postgres-db
          - mongo-db
          - rabbit-mq
      environment:
          - spring.datasource.url=jdbc:postgresql://postgres-db:5432/ethseouldb
          - spring.rabbitmq.host=rabbit-mq
          - network.url=
          - AWS_S3_BUCKET=ethseoulnft
          - AWS_S3_ACCESS_KEY=
          - AWS_S3_SECRET_KEY=
          - DB_CONNECTION_URL=mongodb://root:rootpassword@mongo-db:27017/ethseoul-db?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false
      ports:
          - 5001:5001
    listener:
      build: ./listener  
      depends_on:
          - postgres-db
          - rabbit-mq
      environment:
          - app.run=true
          - spring.datasource.url=jdbc:postgresql://postgres-db:5432/ethseouldb
          - spring.rabbitmq.host=rabbit-mq
          - network.url=https://eth-goerli.blastapi.io/a9aed783-979a-461d-b2d6-0799b73a5e57
    consumer:
      build: ./metadata-consumer 
      depends_on:
          - postgres-db
          - mongo-db
          - rabbit-mq
      environment:
          - spring.datasource.url=jdbc:postgresql://postgres-db:5432/ethseouldb
          - spring.rabbitmq.host=rabbit-mq
          - network.url=
          - AWS_S3_BUCKET=ethseoulnft
          - AWS_S3_ACCESS_KEY=
          - AWS_S3_SECRET_KEY=
          - spring.data.mongodb.uri=mongodb://root:rootpassword@mongo-db:27017/ethseoul-db?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false
    postgres-db:
      image: postgres
      restart: always
      volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
          - POSTGRES_PASSWORD=rootpassword
          - POSTGRES_USER=root
          - POSTGRES_DB=ethseouldb
      ports:
          - 5432:5432
    mongo-db:
      image: mongo
      environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      ports:
          - 27017:27017
    rabbit-mq:
      image: rabbitmq:3.10-management
      environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest
      ports:
          - 5672:5672
          - 15672:15672
          - 8080:8080

volumes:
    sample_db: {}